import './style.css';
import {navegar} from './router.js';import {renderizarProjetos} from './templates.js';import {validarFormulario,mascaras} from './validation.js';import {adicionarCadastro,carregarCadastros,removerCadastro} from './storage.js';
const menu=document.getElementById('navMenu'),toggle=document.getElementById('menuToggle'),contrast=document.getElementById('contrastToggle'),status=document.getElementById('statusA11y');
const setContrast=on=>{document.documentElement.classList.toggle('alto-contraste',on);contrast.setAttribute('aria-pressed',String(on));localStorage.setItem('altoContraste',String(on));status.textContent=on?'Modo de alto contraste ativado.':'Modo de alto contraste desativado.'};
setContrast(localStorage.getItem('altoContraste')==='true');contrast.addEventListener('click',()=>setContrast(!document.documentElement.classList.contains('alto-contraste')));
toggle.addEventListener('click',()=>{const ativo=menu.classList.toggle('ativo');toggle.setAttribute('aria-expanded',String(ativo));toggle.setAttribute('aria-label',ativo?'Fechar menu de navegação':'Abrir menu de navegação')});
window.addEventListener('hashchange',navegar);document.addEventListener('DOMContentLoaded',navegar);
document.addEventListener('viewchange',e=>{menu.classList.remove('ativo');toggle.setAttribute('aria-expanded','false');if(e.detail.rota==='projetos')renderizarProjetos(document.getElementById('listaProjetos'));if(e.detail.rota==='cadastro')iniciarFormulario();if(e.detail.rota==='registros')renderizarCadastros()});
document.addEventListener('click',e=>{const btn=e.target.closest('.saiba-mais');if(btn)Swal.fire({title:btn.dataset.projeto,text:'Conheça e participe das ações do Instituto Esperança.',icon:'info',confirmButtonText:'Entendi',returnFocus:true});const del=e.target.closest('[data-remover]');if(del)confirmarRemocao(del.dataset.remover)});
function iniciarFormulario(){const form=document.getElementById('cadastroForm');['cpf','telefone','cep'].forEach(id=>document.getElementById(id)?.addEventListener('input',e=>e.target.value=mascaras[id](e.target.value)));form?.addEventListener('submit',e=>{e.preventDefault();const dados=Object.fromEntries(new FormData(form));if(!validarFormulario(dados)){status.textContent='O formulário possui campos inválidos. Revise as mensagens de erro.';Swal.fire({title:'Revise o formulário',text:'Existem campos que precisam ser corrigidos.',icon:'error'});return}adicionarCadastro(dados);form.reset();form.querySelectorAll('.valido').forEach(x=>x.classList.remove('valido'));status.textContent='Cadastro realizado com sucesso.';Swal.fire({title:'Cadastro realizado!',text:'Os dados foram salvos no localStorage deste navegador.',icon:'success',confirmButtonText:'OK'})})}
function renderizarCadastros(){const box=document.getElementById('listaCadastros');const lista=carregarCadastros();box.innerHTML=lista.length?lista.map(x=>`<article class="registro"><div><strong>${x.nome}</strong><p>${x.email} • ${x.participacao}</p></div><button class="button danger" data-remover="${x.id}">Excluir <span class="sr-only">cadastro de ${x.nome}</span></button></article>`).join(''):'<p class="alerta">Nenhum cadastro salvo neste navegador.</p>'}
async function confirmarRemocao(id){const r=await Swal.fire({title:'Excluir cadastro?',text:'Esta ação removerá o registro do armazenamento local.',icon:'warning',showCancelButton:true,confirmButtonText:'Excluir',cancelButtonText:'Cancelar',returnFocus:true});if(r.isConfirmed){removerCadastro(id);renderizarCadastros();status.textContent='Cadastro excluído.';Swal.fire({title:'Registro excluído',icon:'success',timer:1300,showConfirmButton:false})}}
